### PR TITLE
Fix work with system qt in containers

### LINKED ISSUE #740: Fail to read configuration
Hello. Sorry for my English.
I am using cqtdelpoyer in a container from a Microsoft image that is used for VS Code development. CQtDeployer (latest version) downloaded from github releases but when trying to package my binary in a directory I get an error

```
vscode ➜ /workspaces/gui_control $ cqtdeployer -bin cmake/gui_control -targetDir GuiControl -qmake /usr/bin/qmake6 -qmlDir cmake/qmls
Info: Deploy ...
Info: The qmake was found in the PATH variable. qmake : /usr/bin/qmake If you want to disable search qmake executable in PATH variable, use the noCheckPATH option
Error: Failed to initialize Qt directories
Error: Deploy failed!
Error: The CQtDeployer fail to read configuration.
vscode ➜ /workspaces/gui_control $ qmake -v
QMake version 3.1
Using Qt version 6.2.4 in /usr/lib/x86_64-linux-gnu
vscode ➜ /workspaces/gui_control $ file cmake/gui_control
cmake/gui_control: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=30e3a18deff195970b202d49f5b1daf66e3237de, for GNU/Linux 3.2.0, with debug_info, not stripped
vscode ➜ /workspaces/gui_control $ ls cmake/qmls
additions  container  elements  menu  notifications  panels  scripts  switcher.qml
```

Container Dockerfile:
```

ARG VARIANT=ubuntu-22.04
FROM mcr.microsoft.com/devcontainers/cpp:0-${VARIANT}

ENV DEBIAN_FRONTEND=nointeractive

RUN sudo apt update

RUN sudo wget https://github.com/QuasarApp/CQtDeployer/releases/download/v1.6.2268/CQtDeployer_1.6.2268.24847be_Linux_x86_64.deb -O /opt/cqtdeployer.deb && \
    sudo dpkg -i /opt/cqtdeployer.deb

#RUN sudo apt install -y snapd
#RUN sudo snap connect cqtdeployer:system-backup && \
#    sudo snap connect cqtdeployer:removable-media && \
#    sudo snap connect cqtdeployer:process-control

RUN sudo apt install -y \
        qt6-base-dev qml-qt6 \ 
        qt6-declarative-dev \
        libqt6serialbus6-dev \
        libqt6serialbus6 \
        libqt6serialbus6-bin \
        libqt6serialport6-dev \
        libqt6serialport6 \
        libgl1-mesa-dev 

```

### PR DESCRIPTION
**Pull request by EndrII**
fix #740

### CODE REVIEW

File: src/Deploy/src/configparser.cpp [hunk 1]
```diff
@@ -1531,7 +1533,7 @@ QList<iDistribution *> ConfigParser::getDistribution() {
         distros.push_back(new ZipArhive(_fileManager));
     }
 
-    if (QuasarAppUtils::Params::isEndable("qif")) {
+    if (QuasarAppUtils::Params::isEndable("qifw") || QuasarAppUtils::Params::isEndable("qif")) {
```
Comment (EndrII) [inline src/Deploy/src/configparser.cpp:1536]:
```suggestion
    if (QuasarAppUtils::Params::isEndable("qif")) {
```
