### PR TITLE
Fix of windows debug extensions

### LINKED ISSUE #763: CQtdeployer sniped TLS plugins on the windows platform.
**Describe the bug**
CQtdeployer sniped TLS plugins on the windows platform.

### PR DESCRIPTION
**Pull request by EndrII**
## Description
From 6.5 Windows version of Qt use a "gebug" extension too.

fix #763

### CODE REVIEW

File: src/Deploy/src/deploycore.cpp [hunk 1]
```diff
@@ -677,7 +677,8 @@ QString DeployCore::findProcess(const QString &env, const QString& proc, bool ig
 }
 
 QStringList DeployCore::debugExtensions() {
-    return {".debug", "d.dll", ".pdb"};
+    // from 6.5 windows version of Qt use a "gebug" extansion too.
```
Comment (EndrII) [inline src/Deploy/src/deploycore.cpp:680]:
```suggestion
    // from 6.5 windows version of Qt use a "gebug" extension too.
```
