### PR TITLE
fix snap version

### LINKED ISSUE #420: snap log message "...command not found"
OS: KDE Neon 5.19.5
Qt: 5.15
command: "cqtdeployer -bin APP_FILE deploySystem noTranslations"
/snap/cqtdeployer/156/bin/desktop-launch: line 163: $'\321\201\321\202\320\276\320\273': command not found

### PR DESCRIPTION
**Pull request by EndrII**
fix paths of the snap version cqtdeployer.
fix #420

### CODE REVIEW

File: Deploy/deploycore.cpp [hunk 1]
```diff
@@ -13,6 +13,7 @@
 
 #include <QDebug>
 #include <QDir>
+#include <QDir>
```
Comment (EndrII) [inline Deploy/deploycore.cpp:16]: dublickate header

**Comment by EndrII** [comment]
build with native qt not working 
```
~/NativeQt$ cqtdeployer -bin NativeQt -qnake /usr/bin/qmake 
Info: Deploy ...
Info: flag targetDir not  used. use default target dir :/home/andrei/NativeQt/DistributionKit
Info: libpq added like a file name mask
Info: libmysqlclient added like a file name mask
Info: libicudata added like a file name mask
Info: libicui18n added like a file name mask
Info: libicuio added like a file name mask
Info: libicule added like a file name mask
Info: libiculx added like a file name mask
Info: libicutest added like a file name mask
Info: libicutu added like a file name mask
Info: libicuuc added like a file name mask
Error: The deployment target requir Qt libs, but init qmake is failed.Use the qmake option for set a path to qmake.
Error: deploy is failed!
```
